#!/bin/bash -x

export GO111MODULE=on 
export GOPROXY=https://goproxy.cn
# build webhook
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o label-customizers
# build docker image
docker build --no-cache -t daocloud.io/daocloud/label-customizers:latest .
rm -rf label-customizers

docker push daocloud.io/daocloud/label-customizers:latest
