apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-label-customizers-cfg
  annotations:
    cert-manager.io/inject-ca-from: cdp-customizer/label-customizers-webhook-cert
  labels:
    app: label-customizers
webhooks:
  - name: mutating-label-customizers.datacreating.com
    clientConfig:
      service:
        name: label-customizers-admission-service
        namespace: cdp-customizer
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
        scope: "Namespaced"
    namespaceSelector:
      matchExpressions:
        # key exist
        - key: monitoring-platform-access1
          operator: Exists
    timeoutSeconds: 5
